Atualização de Padrão
betrybe/sd-0x-project-movie-card-library-crud pull request #23
Opened 2021-02-24 13:59 UTC by LucasSGomide

2021-02-25 13:32 UTC, brunobatista25 requested changes

2021-02-25 13:32 UTC, brunobatista25 commented on README.md
> +  * `git clone git@github.com:tryber/sd-0x-project-movie-card-library-crud-rubric.git`.
remove esse rubric do nome do projeto

2021-02-25 13:32 UTC, brunobatista25 commented on README.md
> +    * `cd sd-0x-project-movie-card-library-crud-rubric`
remove esse rubric do nome do projeto

2021-02-25 13:32 UTC, brunobatista25 commented on README.md
> +  * Vá até a página de _Pull Requests_ do [repositório no GitHub](https://github.com/tryber/sd-0x-project-movie-card-library-crud-rubric/pulls)
remove esse rubric do nome do projeto

2021-02-25 13:32 UTC, brunobatista25 commented on README.md
> +  * Volte até a [página de _Pull Requests_ do repositório](https://github.com/tryber/sd-0x-project-movie-card-library-crud-rubric/pulls) e confira que o seu _Pull Request_ está criado
remove esse rubric do nome do projeto

2021-02-25 13:32 UTC, brunobatista25 commented on README.md
> +Link: [FORMULÁRIO DE AVALIAÇÃO DE PROJETO](https://bit.ly/2OfLJPn)
altera esse link para esse 
Link: [FORMULÁRIO DE AVALIAÇÃO DE PROJETO](https://be-trybe.typeform.com/to/ZTeR4IbH)

2021-02-25 14:11 UTC, brunobatista25 approved these changes

2021-03-03 20:49 UTC, albertosca approved these changes
Presumi que os testes aqui estão iguais aos antigos (fora os describes e its), e que eles só foram divididos em arquivos menores. É isso mesmo, certo?

2021-03-03 20:49 UTC, albertosca commented on README.md
> +**ATENÇÃO!** Muito cuidado com os nomes especificados nos requisitos! O conteúdo deve ser **exatamente igual** ao texto descrito no requisito. Em alguns componentes foram colocadas propriedades chama
```suggestion
**ATENÇÃO!** Muito cuidado com os nomes especificados nos requisitos! O conteúdo deve ser **exatamente igual** ao texto descrito no requisito. Em alguns componentes foram colocadas propriedades chamadas _data-testid_ que, sob nenhuma hipótese devem ser alteradas. Os detalhes acima tem implicação direta no funcionamento do avaliador.
```

2021-03-03 20:49 UTC, albertosca commented on README.md
> +**⚠️ Adicione proptypes a todos os componentes ⚠️**
```suggestion
**⚠️ Adicione PropTypes a todos os componentes ⚠️**
```

2021-03-03 20:49 UTC, albertosca commented on README.md
> +Todos os componentes que recebem _props_ devem ter suas _proptypes_ corretamente declaradas. O _eslint_ checa automaticamente declaração de _proptypes_, portanto seu _Pull Request_ deverá estar com o
```suggestion
Todos os componentes que recebem _props_ devem ter suas _PropTypes_ corretamente declaradas. O _eslint_ checa automaticamente declaração de _PropTypes_, portanto seu _Pull Request_ só receberá nota se elas estiverem feitas.
```

2021-03-03 20:49 UTC, albertosca commented on README.md
> +- Será validado se ao clicar no botão de submit, uma requisição para API é feita, e o filme selecionado é atualizado. Após a conclusão da atualização a pessoa usuária deve ser redirecionada para a pá
```suggestion
- Será validado se, ao clicar no botão de submit, uma requisição para API é feita e o filme selecionado é atualizado. Após a conclusão da atualização a pessoa usuária deve ser redirecionada para a página inicial
```

2021-03-03 20:49 UTC, albertosca commented on src/tests/EditMovie.test.js
> +  it('Será validado se ao clicar no botão de submit, uma requisição para API é feita, e o filme selecionado é atualizado. Após a conclusão da atualização a pessoa usuária deve ser redirecionada para
```suggestion
  it('Será validado se, ao clicar no botão de submit, uma requisição para API é feita e o filme selecionado é atualizado. Após a conclusão da atualização a pessoa usuária deve ser redirecionada para a página inicial', async () => {
```

2021-03-05 11:19 UTC, LucasSGomide commented
> Presumi que os testes aqui estão iguais aos antigos (fora os describes e its), e que eles só foram divididos em arquivos menores. É isso mesmo, certo?

Exatamente @albertosca, apenas separei em arquivos por componente e criei uma pasta "Helpers" para exportar funções que são compartilhadas por vários testes!

2021-03-15 16:35 UTC, merged